#!/bin/bash

binary=yt-dlp

if hash $binary 2>/dev/null ; then
    if [ $# -eq 0 ]; then
        echo "You didn't enter any arguments, dumbass."
    elif [ $1 = "-h" ] || [ $1 = "--help" ]; then
        echo "Usage: video-dl [OPTIONS] URL
        -o, --output           Specifies the output file, without the extension
        -c, --convert          Converts the file to the specified format
        --yt-dl                Use youtube-dl instead of yt-dlp
        -h, --help             Prints this text and exit
        "
    else
        arguments=("$@")
        last_arg=""
        filename=""
        convert=""
        video_url=""

        for arg in "${arguments[@]}"; do
            case $last_arg in
                "-o" | "--output")     filename="$arg" ;;
                "-c" | "--convert")    convert="$arg"  ;;
                "--yt-dl")             binary="yt-dl"  ;;
                "" | *)                video_url="$arg";;
            esac

            last_arg="$arg"
        done

        if [ "$filename" = "" ]; then
            filename="%(title)s"
        fi

        $binary -o "${filename}.%(ext)s" "${video_url}"
        file=$($binary -o "${filename}.%(ext)s" "${video_url}" --get-filename)

        if [ "$convert" = "" ]; then
            :
        else
            ffmpeg -i "${file}" "${file%.*}${convert}"
            rm -f "${file}"
        fi
    fi
else
    echo "You might wanna install $binary for this command buddy."
fi
